# Generated by Django 3.0.3 on 2020-02-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('jobs', 'jobs'), ('it-services', 'it-services'), ('social', 'social'), ('mobiles', 'mobiles'), ('pcs', 'pcs'), ('apps', 'apps'), ('gaming', 'gaming'), ('computing', 'computing'), ('who-is', 'who-is'), ('more-gadgets', 'more-gadgets'), ('tech', 'tech'), ('politics', 'politics'), ('india', 'india'), ('auto', 'auto'), ('buzz', 'buzz'), ('entertainment', 'entertainment')], max_length=20)),
                ('image', models.CharField(max_length=300)),
                ('views', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
    ]
